export const GET_DATA_REQUEST = "GET_DATA_REQUEST"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAILURE = "GET_DATA_FAILURE"


export const GET_FILTER_ITEMS = "GET_FILTER_ITEMS"

export const GET_UPDATED_DATA = "GET_UPDATED_DATA"

export const GET_SELECTED_SEATS = "GET_SELECTED_SEATS";

export const UPDATE_BUS = "UPDATE_BUS";
